services:
  backend:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
      - ./tests:/app/tests

    env_file:
      - .env.${ENVIRONMENT:-dev}

    environment:
      ENVIRONMENT: ${ENVIRONMENT:-dev}

    depends_on:
      - db

    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload

  db:
    image: postgres:15
    container_name: investment-db
    env_file:
      - .env.${ENVIRONMENT:-dev}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data_${ENVIRONMENT:-dev}:/var/lib/postgresql/data

volumes:
  postgres_data_dev:
  postgres_data_test:
  postgres_data_prod:
